# SPDX-License-Identifier: MIT
"""Resolver-consume + fail-closed-verify tests for learned overrides (Cluster B, B3b).

These exercise the DETERMINISTIC override consumer without a model:

  - with NO (or a drifted-sha) overrides the resolver takes ZERO new branches and
    produces an identical ``ResolvedOp`` / identical generated bytes (BACKWARD-COMPAT);
  - a ``reroute_role`` lesson fires ONLY as a last resort on a genuine stub, never on
    a healthy typed resolve, and when it fires it pins ``role_id=requested`` and keeps
    the requested role's appearance (so the body-default heading exclusion still keys
    on the original role);
  - a ``number_format`` swap re-points only the MASK and stays through the legal-type
    gate;
  - ``check_override_targets`` is fail-closed: a now-missing reroute target, a
    non-shell mask, or an uncaptured demo value (incl. an EMPTY inventory) all ERROR;
  - overrides are sha-frozen to the shell (a re-extract empties the consumer).
"""

from __future__ import annotations

import hashlib
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from brandkit.formats.docx import generate as docx_generate
from brandkit.ir import model as ir
from brandkit.profile import schema, store
from brandkit.profile.resolver import ProfileResolver
from brandkit.qa import checks_deterministic as cd

_SHELL = (
    Path(__file__).resolve().parents[0] / "fixtures" / "complex" / "acme_complex.docx"
)


# ---------------------------------------------------------------------------
# Profile builders
# ---------------------------------------------------------------------------
def _docx_profile() -> dict:
    """A docx profile declaring a real body + heading.1 (both shell-backed)."""
    prof = schema.build_envelope("docx", {"name": "t"})
    prof["provenance"]["shell"]["sha256"] = "shell-sha-1"
    prof["roles"] = {
        "_index": ["paragraph", "heading.1"],
        "paragraph": {
            "resolver": {
                "type": "named_style",
                "style_id": "Normal",
                "style_name": "Normal",
            },
            "status": "resolved",
            "confidence": 1.0,
        },
        "heading.1": {
            "resolver": {
                "type": "named_style",
                "style_id": "Heading1",
                "style_name": "Heading 1",
            },
            "status": "resolved",
            "confidence": 1.0,
        },
    }
    return prof


def _present_reroute(prof: dict, requested: str, target: str) -> dict:
    """Stamp a present, sha-bound reroute lesson onto ``prof``."""
    ov = prof["rules"]["overrides"]
    ov["status"] = "present"
    ov["source_shell_sha256"] = prof["provenance"]["shell"]["sha256"]
    ov["reroute_roles"] = {requested: target}
    return prof


# ---------------------------------------------------------------------------
# BACKWARD-COMPAT: no overrides ⇒ zero new branches
# ---------------------------------------------------------------------------
class NoOverridesByteIdenticalTest(unittest.TestCase):
    def test_resolve_role_identical_with_absent_overrides(self):
        """An absent overrides block leaves resolve_role byte-identical."""
        base = _docx_profile()
        # Default build_envelope already stamps an ``absent`` overrides block.
        self.assertEqual(base["rules"]["overrides"]["status"], "absent")
        op = ProfileResolver(base).resolve_role("heading.1")
        # The override indexes are EMPTY (zero new branches).
        r = ProfileResolver(base)
        self.assertEqual(r._overrides, {})
        self.assertEqual(r._number_format_swaps, {})
        # A missing role with no lesson still falls back to the stub/paragraph path.
        stub = ProfileResolver(base).resolve_role("heading.9", fallback="paragraph")
        self.assertEqual(stub.role_id, "paragraph")  # fell back, no reroute
        # Healthy resolve is unchanged.
        self.assertEqual(op.role_id, "heading.1")
        self.assertEqual(op.resolver.get("style_id"), "Heading1")

    def test_drifted_sha_takes_zero_new_branches(self):
        """A present lesson whose sha no longer matches is NOT consumed."""
        prof = _present_reroute(_docx_profile(), "heading.9", "heading.1")
        prof["provenance"]["shell"]["sha256"] = "shell-sha-2"  # drift
        self.assertFalse(store.overrides_are_present(prof))
        r = ProfileResolver(prof)
        self.assertEqual(r._overrides, {})  # frozen out
        # heading.9 falls back to paragraph (today's behavior), NOT rerouted.
        op = r.resolve_role("heading.9", fallback="paragraph")
        self.assertEqual(op.role_id, "paragraph")

    @unittest.skipUnless(_SHELL.exists(), "complex docx fixture missing")
    def test_generated_bytes_identical_absent_vs_empty_block(self):
        """docx generate() output is identical whether overrides is the shaped
        ``absent`` block or the legacy reserved-empty ``{}``."""
        idoc = ir.IntermediateDocument(
            blocks=[
                ir.Heading(level=1, runs=[{"t": "Title"}]),
                ir.Paragraph(runs=[{"t": "Body."}]),
            ]
        )

        def _hash(prof: dict) -> str:
            with tempfile.TemporaryDirectory() as td:
                out = Path(td) / "o.docx"
                docx_generate.generate(prof, _SHELL, idoc, out)
                return hashlib.sha256(out.read_bytes()).hexdigest()

        absent = _docx_profile()
        legacy = _docx_profile()
        legacy["rules"]["overrides"] = {}  # pre-B3 reserved slot
        self.assertEqual(_hash(absent), _hash(legacy))


# ---------------------------------------------------------------------------
# Reroute fires ONLY on a stub
# ---------------------------------------------------------------------------
class RerouteOnlyOnStubTest(unittest.TestCase):
    def test_healthy_typed_resolve_is_not_rerouted(self):
        """A reroute lesson for a role that already resolves healthily is ignored."""
        prof = _present_reroute(_docx_profile(), "heading.1", "paragraph")
        self.assertTrue(store.overrides_are_present(prof))
        op = ProfileResolver(prof).resolve_role("heading.1")
        # heading.1 is a healthy typed resolve ⇒ NOT rerouted to paragraph.
        self.assertEqual(op.role_id, "heading.1")
        self.assertEqual(op.resolver.get("style_id"), "Heading1")

    def test_stub_from_missing_role_is_rerouted(self):
        """A genuinely-absent role (no fallback) is rerouted to the target role."""
        prof = _present_reroute(_docx_profile(), "heading.9", "heading.1")
        op = ProfileResolver(prof).resolve_role("heading.9", fallback=None)
        # Rerouted: it now carries heading.1's resolver, pinned to the requested id.
        self.assertEqual(op.role_id, "heading.9")
        self.assertEqual(op.resolver.get("style_id"), "Heading1")

    def test_empty_resolver_role_is_rerouted(self):
        """A role that EXISTS but has an empty resolver ({}) is a stub ⇒ rerouted."""
        prof = _docx_profile()
        prof["roles"]["_index"].append("heading.2")
        prof["roles"]["heading.2"] = {"resolver": {}, "status": "stub"}
        _present_reroute(prof, "heading.2", "heading.1")
        op = ProfileResolver(prof).resolve_role("heading.2", fallback=None)
        self.assertEqual(op.role_id, "heading.2")
        self.assertEqual(op.resolver.get("style_id"), "Heading1")

    def test_reroute_target_stub_yields_stub(self):
        """Single-hop: if the target itself resolves to a stub, no fabrication."""
        prof = _present_reroute(_docx_profile(), "heading.9", "role.absent")
        op = ProfileResolver(prof).resolve_role("heading.9", fallback=None)
        # role.absent does not exist ⇒ target resolves to an empty stub; the rerouted
        # op carries that empty resolver (never a fabricated target).
        self.assertEqual(op.role_id, "heading.9")
        self.assertEqual(op.resolver, {})

    def test_reroute_does_not_recurse_on_chain(self):
        """Single-hop only: A->B is resolved without re-applying B's own lesson."""
        prof = _docx_profile()
        ov = prof["rules"]["overrides"]
        ov["status"] = "present"
        ov["source_shell_sha256"] = prof["provenance"]["shell"]["sha256"]
        # heading.9 -> heading.8 -> heading.1; heading.8 is itself absent.
        ov["reroute_roles"] = {"heading.9": "heading.8", "heading.8": "heading.1"}
        op = ProfileResolver(prof).resolve_role("heading.9", fallback=None)
        # heading.9 reroutes to heading.8 (single hop); heading.8 is absent and is NOT
        # itself rerouted (depth guard) ⇒ the rerouted op is heading.8's stub.
        self.assertEqual(op.role_id, "heading.9")
        self.assertEqual(op.resolver, {})


# ---------------------------------------------------------------------------
# Reroute preserves role_id + appearance gate
# ---------------------------------------------------------------------------
class ReroutePreservesRoleIdAndAppearanceTest(unittest.TestCase):
    def _prof_with_body_default(self) -> dict:
        prof = _docx_profile()
        # A document body size/color default that must NOT leak onto a heading.
        prof["theme"] = {
            "fonts": {"body": {"latin": "Roboto", "size_hp": 22}},
            "text": {"body": {"color": {"kind": "hex", "hex": "1F4E79"}}},
        }
        return prof

    def test_rerouted_heading_keeps_requested_role_id(self):
        prof = _present_reroute(
            self._prof_with_body_default(), "heading.9", "paragraph"
        )
        op = ProfileResolver(prof).resolve_role("heading.9", fallback=None)
        self.assertEqual(op.role_id, "heading.9")
        # Inherited paragraph's resolver verbatim (shell-proven Normal style).
        self.assertEqual(op.resolver.get("style_id"), "Normal")

    def test_rerouted_heading_excluded_from_body_default(self):
        """The body size/color default keys on the ORIGINAL heading role, so a
        rerouted heading.9 does NOT get the body size/color leaked onto it."""
        prof = self._prof_with_body_default()
        _present_reroute(prof, "heading.9", "paragraph")
        heading_op = ProfileResolver(prof).resolve_role("heading.9", fallback=None)
        # The body FONT flows everywhere (v1 behavior); the body SIZE/COLOR must NOT.
        self.assertEqual(
            (heading_op.appearance.get("font") or {}).get("latin"), "Roboto"
        )
        self.assertIsNone(heading_op.appearance.get("size_hp"))
        self.assertIsNone(heading_op.appearance.get("color"))

    def test_paragraph_reroute_keeps_body_default(self):
        """A rerouted paragraph.* (body family) still receives the body default."""
        prof = self._prof_with_body_default()
        _present_reroute(prof, "paragraph.lead", "paragraph")
        op = ProfileResolver(prof).resolve_role("paragraph.lead", fallback=None)
        self.assertEqual(op.role_id, "paragraph.lead")
        self.assertEqual(op.appearance.get("size_hp"), 22)
        self.assertEqual((op.appearance.get("color") or {}).get("hex"), "1F4E79")


# ---------------------------------------------------------------------------
# number_format swap (xlsx) — resolver + membership
# ---------------------------------------------------------------------------
def _xlsx_profile() -> dict:
    prof = schema.build_envelope("xlsx", {"name": "t"})
    prof["provenance"]["shell"]["sha256"] = "xlsx-sha-1"
    prof["roles"] = {
        "_index": ["metric.value"],
        "metric.value": {
            "resolver": {"type": "number_format", "number_format": "0.00"},
            "status": "resolved",
            "confidence": 1.0,
        },
    }
    return prof


class NumberFormatSwapTest(unittest.TestCase):
    def _present_swap(self, prof: dict, role: str, mask: str) -> dict:
        ov = prof["rules"]["overrides"]
        ov["status"] = "present"
        ov["source_shell_sha256"] = prof["provenance"]["shell"]["sha256"]
        ov["number_format_swaps"] = {role: mask}
        return prof

    def test_swap_rewrites_mask_and_stays_typed(self):
        prof = self._present_swap(_xlsx_profile(), "metric.value", "#,##0")
        op = ProfileResolver(prof).resolve_role("metric.value", fallback=None)
        # The mask is swapped verbatim; the op stays a legal number_format op.
        self.assertEqual(op.resolver.get("type"), "number_format")
        self.assertEqual(op.resolver.get("number_format"), "#,##0")

    def test_swap_ignored_when_overrides_absent(self):
        prof = _xlsx_profile()  # absent overrides
        op = ProfileResolver(prof).resolve_role("metric.value", fallback=None)
        self.assertEqual(op.resolver.get("number_format"), "0.00")

    def test_swap_membership_against_shell(self):
        """A swap mask the shell uses passes; one it does not is an ERROR."""
        prof = self._present_swap(_xlsx_profile(), "metric.value", "#,##0")

        class _FakeShell:
            pass

        # Stub the shell readers: the shell uses {#,##0} but not {0%}.
        orig = cd._xlsx_number_format_masks
        cd._xlsx_number_format_masks = lambda shell: {"#,##0"}
        cd._xlsx_defined_names_orig = cd._xlsx_defined_names
        cd._xlsx_defined_names = lambda shell: set()
        try:
            ok = cd.check_override_targets(_FakeShell(), prof)
            self.assertEqual(ok, [])  # #,##0 is a used mask
            bad = self._present_swap(_xlsx_profile(), "metric.value", "0%")
            errs = cd.check_override_targets(_FakeShell(), bad)
            self.assertTrue(errs)
            self.assertEqual(errs[0].check, "override_targets_exist")
            self.assertEqual(errs[0].severity, schema.Severity.ERROR.value)
        finally:
            cd._xlsx_number_format_masks = orig
            cd._xlsx_defined_names = cd._xlsx_defined_names_orig
            del cd._xlsx_defined_names_orig


# ---------------------------------------------------------------------------
# check_override_targets — fail-closed
# ---------------------------------------------------------------------------
class CheckOverrideTargetsFailClosedTest(unittest.TestCase):
    def test_noop_when_overrides_absent(self):
        prof = _docx_profile()  # absent
        self.assertEqual(cd.check_override_targets(object(), prof), [])

    def test_reroute_to_undeclared_role_errors(self):
        prof = _present_reroute(_docx_profile(), "heading.9", "role.not.declared")
        errs = cd.check_override_targets(object(), prof)
        self.assertTrue(any(f.check == "override_targets_exist" for f in errs))
        self.assertTrue(all(f.severity == schema.Severity.ERROR.value for f in errs))

    def test_reroute_target_not_shell_backed_errors(self):
        """A declared target whose resolver target the shell does NOT prove ERRORs."""
        prof = _present_reroute(_docx_profile(), "heading.9", "heading.1")

        # The shell does NOT carry Heading1/Heading 1 (now-missing target).
        orig = cd._docx_style_keys
        cd._docx_style_keys = lambda shell: {"Normal"}
        try:
            errs = cd.check_override_targets(object(), prof)
            self.assertTrue(errs)
            self.assertEqual(errs[0].check, "override_targets_exist")
            self.assertEqual(errs[0].severity, schema.Severity.ERROR.value)
        finally:
            cd._docx_style_keys = orig

    def test_demo_clear_empty_inventory_rejects(self):
        """reject-on-empty: a demo_clear value with NO captured set is an ERROR."""
        prof = _docx_profile()
        ov = prof["rules"]["overrides"]
        ov["status"] = "present"
        ov["source_shell_sha256"] = prof["provenance"]["shell"]["sha256"]
        ov["demo_clears"] = ["Lorem ipsum"]
        # No comprehension / surface demo set ⇒ captured set is EMPTY ⇒ reject.
        errs = cd.check_override_targets(None, prof)  # shell=None ok for demo branch
        self.assertTrue(errs)
        self.assertEqual(errs[0].check, "override_targets_exist")
        self.assertEqual(errs[0].severity, schema.Severity.ERROR.value)

    def test_demo_clear_membership_passes_when_captured(self):
        prof = _docx_profile()
        # Surface a captured demo region marker so the value is a known demo string.
        prof["surface"] = {
            "docx": {"demo_region": {"instruction_markers": ["Lorem ipsum"]}}
        }
        ov = prof["rules"]["overrides"]
        ov["status"] = "present"
        ov["source_shell_sha256"] = prof["provenance"]["shell"]["sha256"]
        ov["demo_clears"] = ["Lorem ipsum"]
        self.assertEqual(cd.check_override_targets(None, prof), [])

    def test_reroute_present_passes_when_shell_backed(self):
        prof = _present_reroute(_docx_profile(), "heading.9", "heading.1")
        orig = cd._docx_style_keys
        cd._docx_style_keys = lambda shell: {"Normal", "Heading1", "Heading 1"}
        try:
            self.assertEqual(cd.check_override_targets(object(), prof), [])
        finally:
            cd._docx_style_keys = orig


# ---------------------------------------------------------------------------
# Overrides frozen to the shell
# ---------------------------------------------------------------------------
class OverridesFrozenToShellTest(unittest.TestCase):
    def test_reextract_drift_reverts_resolver(self):
        prof = _present_reroute(_docx_profile(), "heading.9", "heading.1")
        # Present + current ⇒ rerouted.
        live = ProfileResolver(prof).resolve_role("heading.9", fallback=None)
        self.assertEqual(live.resolver.get("style_id"), "Heading1")
        # A re-extract re-stamps provenance.shell.sha256 (store.save_profile): the
        # recorded sha no longer matches ⇒ the lesson is frozen out, behavior reverts.
        prof["provenance"]["shell"]["sha256"] = "re-extracted-sha"
        reverted = ProfileResolver(prof).resolve_role("heading.9", fallback=None)
        self.assertEqual(reverted.resolver, {})  # back to today's stub


if __name__ == "__main__":
    unittest.main()
